### PR TITLE
remove logic from __init__.py and break import cycles

### LINKED ISSUE #622: circular imports and busy __init__.py files
currently we're getting lucky that things work nicely despite abusing imports. for example, when trying to use MonkeyType:

```
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/code/capa-pub/capa/features/freeze.py", line 58, in <module>
    import capa.features.insn
  File "/home/user/code/capa-pub/capa/features/insn.py", line 9, in <module>
    import capa.render.utils
  File "/home/user/code/capa-pub/capa/render/__init__.py", line 11, in <module>
    import capa.rules
  File "/home/user/code/capa-pub/capa/rules.py", line 88, in <module>
    capa.features.insn.API,
AttributeError: module 'capa.features' has no attribute 'insn'
```

I get a similar error in VS Code from pylance:

image

and can reproduce an import issue locally:

image

---

`capa/features/__init__.py` defines `Feature`, `String`, `Regex` and some other stuff. also, there are files in the same directory, like `insn.py` and `file.py`.

when you ask to do `import capa.features.insn.API`:
`insn.py` imports `render` imports `rules` references `capa.features.insn.API` which is itself (circular import)  and is further complicated by the fact that python looks in `capa/features/__init__.py` first.

we should fix the circular dependency and the `__init__`/`insn` split.

---

in summary, we have a web of code and dependencies spread among `__init__.py` files and `*.py` files. some of the `*.py` files import from their parents through their dependencies. things somehow work, but it doesn't seem correct, and is preventing me from using MonkeyType easily.

i propose that we refactor our use of `__init__.py` to keep those bare and move code into shared/sub modules. unfortunately, this will be a breaking change, as the location of some of these functions/classes changes. so, we should assess if we can/want to do this before 2.0 and get it in.

---
https://github.com/Khan/style-guides/blob/master/style/python.md#__init__py

### PR DESCRIPTION
**Pull request by williballenthin**
closes #622 

### Checklist

- [ ] No CHANGELOG update needed

- [x] No new tests needed

- [x] No documentation update needed

### CODE REVIEW

**Comment by williballenthin** [comment]
- [ ] capa/__init__.py
  - [ ] capa/features/__init__.py
  - [ ] capa/features/extractors/__init__.py
  - [ ] capa/features/extractors/ida/__init__.py
  - [ ] capa/features/extractors/pefile/__init__.py
  - [ ] capa/features/extractors/smda/__init__.py
  - [ ] capa/features/extractors/viv/__init__.py
  - [ ] capa/ida/__init__.py
  - [ ] capa/ida/helpers/__init__.py
  - [ ] capa/ida/plugin/__init__.py
  - [ ] capa/render/__init__.py

**Comment by williballenthin** [comment]
logic is moved out of `__init__.py`, still need to fix at least one circular import:

image

**Comment by williballenthin** [comment]
read the linked issue for an explanation of what this PR does. basically, cleans up `__init__py` and breaks some import cycles. i don't think there's much risk here; just make sure you understand some classes/functions have moved slightly.

also, as i did this, i fixed a whole bunch of import warnings highlighted by pylance (VS Code). that will be a very nice code quality improvement side effect of this PR.

**Review by mr-tz — APPROVED** [review]
I skimmed over this. Thanks for all the fixes. I think it's a good time to get this in before 2.0.
I'm confident in our tests and will do some manual checks as well.

**Pull request merged**
