### PR TITLE
fixes 191

### PR DESCRIPTION
**Pull request by mike-hunhoff**
Adding additional check for `jmp` instruction when detecting loops with viv extractor.

### CODE REVIEW

**Comment by williballenthin** [comment]
can you run `black -l 120 .` to fix the style? otherwise, looks good

**Comment by mike-hunhoff** [comment]
> can you run `black -l 120 .` to fix the style? otherwise, looks good

```
C:\Exclusions\capa> black -l 120 .
All done! ✨ 🍰 ✨
57 files left unchanged.
```
`black` doesn't complain on my end 🤔

**Comment by re-fox** [comment]
FWIW I pulled and tested this branch and it looks like it now catches the logic that I posted in my issue.  Thank you @mike-hunhoff .

**Comment by Ana06** [comment]
@mike-hunhoff 

> > can you run `black -l 120 .` to fix the style? otherwise, looks good
> 
> ```
> C:\Exclusions\capa> black -l 120 .
> All done! ✨ 🍰 ✨
> 57 files left unchanged.
> ```
> 
> `black` doesn't complain on my end 🤔

This is weird... 😕 I'll take a look

**Comment by Ana06** [comment]
It is fixed! 🎉 But honestly I don't know why it was not working, because exactly the same code/commits work here https://github.com/Ana06/capa/pull/1 Re-running the job didn't fix the issue, but rebasing to current master and pushing did 😕  I'll write GitHub, maybe it is a bug or they have any clue why this happened...

**Comment by mike-hunhoff** [comment]
Thank you for checking @re-fox and thank you for solving the formatting issue @Ana06.

**Pull request merged**
