### PR TITLE
add render to dict, is the same as default but just in dictionary so …

### PR DESCRIPTION
**Pull request by doomedraven**
…simplifies the integrations

```
{'ATT&CK': {'COLLECTION': ['Input Capture::Keylogging [T1056.001]'],
            'DEFENSE EVASION': ['Obfuscated Files or Information [T1027]',
                                'Virtualization/Sandbox Evasion::System Checks '
                                '[T1497.001]'],
            'DISCOVERY': ['File and Directory Discovery [T1083]',
                          'Query Registry [T1012]',
                          'System Information Discovery [T1082]'],
            'EXECUTION': ['Shared Modules [T1129]']},
 'CAPABILITY': {'accept command line arguments': 'host-interaction/cli',
                'allocate thread local storage (2 matches)': 'host-interaction/process',
                'check for time delay via GetTickCount': 'anti-analysis/anti-debugging/debugger-detection',
                'check if process is running under wine': 'anti-analysis/anti-emulation/wine',
                'contain a resource (.rsrc) section': 'executable/pe/section/rsrc',
                'create registry key (2 matches)': 'host-interaction/registry/create',
                'delete registry key': 'host-interaction/registry/delete',
                'encrypt data using RC4 PRGA': 'data-manipulation/encryption/rc4',
                'execute anti-VM instructions': 'anti-analysis/anti-vm/vm-detection',
                'extract resource via kernel32 functions (7 matches)': 'executable/resource',
                'get OS version (3 matches)': 'host-interaction/os/version',
                'get disk information': 'host-interaction/hardware/storage',
                'get file attributes': 'host-interaction/file-system/meta',
                'get file size (2 matches)': 'host-interaction/file-system/meta',
                'get file version info (2 matches)': 'host-interaction/file-system/meta',
                'get system information': 'host-interaction/os/info',
                'get thread local storage value (3 matches)': 'host-interaction/process',
                'link function at runtime (13 matches)': 'linking/runtime-linking',
                'link many functions at runtime (2 matches)': 'linking/runtime-linking',
                'log keystrokes via polling (3 matches)': 'collection/keylog',
                'parse PE header (8 matches)': 'load-code/pe',
                'query environment variable': 'host-interaction/environment-variable',
                'query registry entry (3 matches)': 'host-interaction/registry/query',
                'query registry value (3 matches)': 'host-interaction/registry/query',
                'read file (2 matches)': 'host-interaction/file-system/read',
                'reference anti-VM strings targeting Xen': 'anti-analysis/anti-vm/vm-detection',
                'set application hook (6 matches)': 'host-interaction/gui',
                'set environment variable': 'host-interaction/environment-variable',
                'set file attributes': 'host-interaction/file-system/meta',
                'set thread local storage value (2 matches)': 'host-interaction/process',
                'terminate process (4 matches)': 'host-interaction/process/terminate',
                'write file (3 matches)': 'host-interaction/file-system/write'},
 'MBC': {'ANTI-BEHAVIORAL ANALYSIS': ['Debugger Detection::Timing/Delay Check '
                                      'GetTickCount [B0001.032]',
                                      'Emulator Detection [B0004]',
                                      'Virtual Machine Detection::Instruction '
                                      'Testing [B0009.029]',
                                      'Virtual Machine Detection [B0009]'],
         'COLLECTION': ['Keylogging::Polling [F0002.002]'],
         'CRYPTOGRAPHY': ['Encrypt Data::RC4 [C0027.009]',
                          'Generate Pseudo-random Sequence::RC4 PRGA '
                          '[C0021.004]']}}
```

### CODE REVIEW

**Comment by doomedraven** [comment]
for testing:

```
file = "479f0c83ec531f8caced9b7c663c5dbc600c42d6ee39567a97ebc1ef1bab398e"
import json
import capa.main
import capa.rules
import capa.engine
import capa.features
from pprint import pprint as pp
from capa.engine import *
capa.main.RULES_PATH_DEFAULT_STRING = "/tmp/capa/rules/"
rules_path = "/tmp/capa/rules/"
rules = capa.main.get_rules(capa.main.RULES_PATH_DEFAULT_STRING, disable_progress=True)
rules = capa.rules.RuleSet(rules)
extractor = capa.main.get_extractor(file, "auto", disable_progress=True)
meta = capa.main.collect_metadata("", file,capa.main.RULES_PATH_DEFAULT_STRING, "auto", extractor)
capabilities, counts = capa.main.find_capabilities(rules, extractor, disable_progress=True)
meta["analysis"].update(counts)
#capa_resuls = json.loads(capa.render.render_json(meta, rules, capabilities))
details = capa.render.render_dictionary(meta, rules, capabilities)
pp(details)
```

**Comment by doomedraven** [comment]
improved the output format

```
>>> pp(details)
{'ATT&CK': {'COLLECTION': ['Input Capture::Keylogging [T1056.001]'],
            'DEFENSE EVASION': ['Obfuscated Files or Information [T1027]',
                                'Virtualization/Sandbox Evasion::System Checks '
                                '[T1497.001]'],
            'DISCOVERY': ['File and Directory Discovery [T1083]',
                          'Query Registry [T1012]',
                          'System Information Discovery [T1082]'],
            'EXECUTION': ['Shared Modules [T1129]']},
 'CAPABILITY': {'anti-analysis/anti-debugging/debugger-detection': ['check for '
                                                                    'time '
                                                                    'delay via '
                                                                    'GetTickCount'],
                'anti-analysis/anti-emulation/wine': ['check if process is '
                                                      'running under wine'],
                'anti-analysis/anti-vm/vm-detection': ['execute anti-VM '
                                                       'instructions',
                                                       'reference anti-VM '
                                                       'strings targeting Xen'],
                'collection/keylog': ['log keystrokes via polling (3 matches)'],
                'data-manipulation/encryption/rc4': ['encrypt data using RC4 '
                                                     'PRGA'],
                'executable/pe/section/rsrc': ['contain a resource (.rsrc) '
                                               'section'],
                'executable/resource': ['extract resource via kernel32 '
                                        'functions (7 matches)'],
                'host-interaction/cli': ['accept command line arguments'],
                'host-interaction/environment-variable': ['query environment '
                                                          'variable',
                                                          'set environment '
                                                          'variable'],
                'host-interaction/file-system/meta': ['get file attributes',
                                                      'get file size (2 '
                                                      'matches)',
                                                      'get file version info '
                                                      '(2 matches)',
                                                      'set file attributes'],
                'host-interaction/file-system/read': ['read file (2 matches)'],
                'host-interaction/file-system/write': ['write file (3 '
                                                       'matches)'],
                'host-interaction/gui': ['set application hook (6 matches)'],
                'host-interaction/hardware/storage': ['get disk information'],
                'host-interaction/os/info': ['get system information'],
                'host-interaction/os/version': ['get OS version (3 matches)'],
                'host-interaction/process': ['allocate thread local storage (2 '
                                             'matches)',
                                             'get thread local storage value '
                                             '(3 matches)',
                                             'set thread local storage value '
                                             '(2 matches)'],
                'host-interaction/process/terminate': ['terminate process (4 '
                                                       'matches)'],
                'host-interaction/registry/create': ['create registry key (2 '
                                                     'matches)'],
                'host-interaction/registry/delete': ['delete registry key'],
                'host-interaction/registry/query': ['query registry entry (3 '
                                                    'matches)',
                                                    'query registry value (3 '
                                                    'matches)'],
                'linking/runtime-linking': ['link function at runtime (13 '
                                            'matches)',
                                            'link many functions at runtime (2 '
                                            'matches)'],
                'load-code/pe': ['parse PE header (8 matches)']},
 'MBC': {'ANTI-BEHAVIORAL ANALYSIS': ['Debugger Detection::Timing/Delay Check '
                                      'GetTickCount [B0001.032]',
                                      'Emulator Detection [B0004]',
                                      'Virtual Machine Detection::Instruction '
                                      'Testing [B0009.029]',
                                      'Virtual Machine Detection [B0009]'],
         'COLLECTION': ['Keylogging::Polling [F0002.002]'],
         'CRYPTOGRAPHY': ['Encrypt Data::RC4 [C0027.009]',
                          'Generate Pseudo-random Sequence::RC4 PRGA '
                          '[C0021.004]']},
 'md5': '6498aeebd66481772668cb3f64ce6bf7',
 'path': '479f0c83ec531f8caced9b7c663c5dbc600c42d6ee39567a97ebc1ef1bab398e',
 'sha1': 'dcf5db0d293cdcaf913e45f55feba7f27ee4d8d3',
 'sha256': '479f0c83ec531f8caced9b7c663c5dbc600c42d6ee39567a97ebc1ef1bab398e'}
```
Screenshot 2020-12-01 at 20 27 37

Screenshot 2020-12-01 at 20 27 32

**Comment by williballenthin** [comment]
hey @doomedraven, thanks for contributing this additional rendering code to capa. i love the integration you have going with cape!

would you consider moving this rendering code into your example script? while the new output dictionary is certainly simpler than the existing json report format, it duplicates the existing json report to support an external integration that's outside of the core capa tool. we're hesitant to support this new code when its not used by the capa cli tool. for integrating with external systems, like cape, using capa as a library and translating the results is a great way to go; alternatively, we include the json output format in our testing and semver guarantees, so you can rely on this format (for example, this is what we use for some of our internal services).

to be clear, we're open to more discussion on this topic. before we released capa, we discussed guidelines on how to handle external integrations, and we want to be 100% fair and inclusive of your contributions.

**Comment by doomedraven** [comment]
hello, yes for sure, i will commit that in a bit

**Comment by doomedraven** [comment]
@williballenthin something like this?

**Comment by williballenthin** [comment]
looks great to me! @mr-tz any concerns?

**Comment by mr-tz** [comment]
No, please fix the code style issue (`isort`) and then we can merge.

**Comment by doomedraven** [comment]
done :)

**Comment by doomedraven** [comment]
i will check in a bit why it fails, as i can't get it working in local with `isort --profile black --length-sort --line-width 120 -c capa_as_library.py`

**Comment by mr-tz** [comment]
Thanks, it can be annoying, make sure you use the same versions of `black` and `isort` as used in CI: https://github.com/fireeye/capa/pull/375/checks?check_run_id=1519692919#step:4:1

**Comment by doomedraven** [comment]
ok now looks good, learned something new, it will fails on py2 due to type hints

**Comment by mr-tz** [comment]
Thank you!

**Comment by doomedraven** [comment]
thanks for great tool ;)

**Pull request merged**
