### PR TITLE
setup: bump viv to 0.2.0

### LINKED ISSUE #201: update viv once vivisect#297 (delayed imports) lands
the viv PE parser doesn't support delayed imports. contribute this feature, and then bump the viv version that capa depends on.

### LINKED ISSUE #385: Exception: Read gave wrong length
### Description

This could be a viv bug.

```
Exception: Read gave wrong length at va: 0x140000ffc (wanted 8 got 4)
```

### Steps to Reproduce

1. `python2 scripts/show-features.py -F 0x140001020 40c0a313897b26e14e54683ceace4a161859f368b0114a2ca614deca3b2ca5da`
The following error is produced
```
  File "scripts/show-features.py", line 190, in <module>
    sys.exit(main())
  File "scripts/show-features.py", line 107, in main
    vw = capa.main.get_workspace(args.sample, args.format)
  File "/usr/lib/python2.7/site-packages/flare_capa-1.4.0-py2.7.egg/capa/main.py", line 267, in get_workspace
    vw = viv_utils.getWorkspace(path, should_save=should_save)
  File "/usr/lib/python2.7/site-packages/viv_utils-0.3.17-py2.7.egg/viv_utils/__init__.py", line 86, in getWorkspace
    vw.loadFromFile(fp)
  File "/usr/lib/python2.7/site-packages/vivisect-0.1.0-py2.7.egg/vivisect/__init__.py", line 2480, in loadFromFile
    fname = mod.parseFile(self, filename, baseaddr=baseaddr)
  File "/usr/lib/python2.7/site-packages/vivisect-0.1.0-py2.7.egg/vivisect/parsers/pe.py", line 36, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename, baseaddr=baseaddr)
  File "/usr/lib/python2.7/site-packages/vivisect-0.1.0-py2.7.egg/vivisect/parsers/pe.py", line 333, in loadPeIntoWorkspace
    mapoffset = vw.readMemoryPtr(rva + baseaddr) - baseaddr
  File "/usr/lib/python2.7/site-packages/vivisect-0.1.0-py2.7.egg/envi/memory.py", line 189, in readMemoryPtr
    return self.readMemValue(va, self.imem_psize)
  File "/usr/lib/python2.7/site-packages/vivisect-0.1.0-py2.7.egg/envi/memory.py", line 178, in readMemValue
    raise Exception("Read gave wrong length at va: 0x%.8x (wanted %d got %d)" % (addr, size, len(bytes)))
Exception: Read gave wrong length at va: 0x140000ffc (wanted 8 got 4)
```

**Expected behavior:**
Executable to be processed

**Actual behavior:**
Exception is raised

### Versions
Master from git

### Additional Information
Sample is attached here  (password infected)
[mal.zip](https://github.com/fireeye/capa/files/5703693/mal.zip)

### PR DESCRIPTION
**Pull request by williballenthin**
closes #385
closes #201

### CODE REVIEW

**Comment by williballenthin** [comment]
looks like analysis changed and broke one test:

**Comment by williballenthin** [comment]
issue reported upstream

**Comment by williballenthin** [comment]
using `show-features`:

```
$python ./scripts/show-features.py --function 0x46d6ce mimikatz.exe_ | grep insn | sort | less
...
insn: 0x0046d7d8: mnemonic(jmp) <-- expected other instructions flowing from this, like 0x46D9CA, 0x46D7DF, and 0x46DA23
insn: 0x0046d7d8: offset(0x0)
insn: 0x0046d7d8: offset/x32(0x0)
insn: 0x0046e12e: mnemonic(mov)
insn: 0x0046e134: mnemonic(mov)
insn: 0x0046e13a: mnemonic(xor)
...
```

**Comment by williballenthin** [comment]
this isn't going to make it into v1.5.0 due to viv merging a huge PR before releasing viv 0.2.1

**Comment by Ana06** [comment]
I also noticed that `parse PE header` gets 1 match less (40 instead of 41) with mimikatz.exe_ and vivisect 0.2.0. This doesn't seem to be related to the missing switch. 🤔

**Comment by Ana06** [comment]
The test that is failing here works with Python3: https://github.com/fireeye/capa/pull/421

**Comment by mr-tz** [comment]
tests in `0.2.1` succeed in #454

**Pull request closed without merging**
