### PR TITLE
extract ordinal and name imports

### PR DESCRIPTION
**Pull request by mr-tz**
if name and ordinal are present provide both of these import features

### CODE REVIEW

**Review by williballenthin — APPROVED** [review]

**Comment by williballenthin** [comment]
since your example comes from mimikatz, would you add a test for this?

then we can be sure viv also handles this correctly

**Comment by mr-tz** [comment]
vivisect only knows of the import by ordinal: `file: 0x004731d0: import(cabinet.#11)`

**Comment by mr-tz** [comment]
It doesn't appear that vivisect makes both import by ordinal and name available. Should we remove the IDA feature or accept the discrepancy?

**Comment by williballenthin** [comment]
i'd say we should accept the discrepancy. i'd lean on the side of having more info when possible. i see this as an issue with viv.

**Comment by mr-tz** [comment]
Thanks, I've added an IDA specific test for this (see last row in image below).



All tests pass.

**Pull request merged**
