### PR TITLE
v1.5.0

### PR DESCRIPTION
**Pull request by williballenthin**

### CODE REVIEW

**Comment by williballenthin** [comment]
image

**Comment by williballenthin** [comment]
image

**Comment by williballenthin** [comment]
linter thorough is taking hours. running in background. dont necessarily see this as a blocker to release.

**Review by Ana06 — APPROVED** [review]
Thanks for taking care of this @williballenthin 💘 This looks great!

[nitpick] I personally wouldn't add CI changes to the new features list as I expect that list to include the features relevant for the final users. CI improvements help the developers but not really the users.

**Review by mike-hunhoff — APPROVED** [review]
Awesome, thank you Willi. lgtm 🚀

**Comment by williballenthin** [comment]
@Ana06 fair, but i want to recognize the work that @mr-tz did! though i agree most people won't recognize what this means.

**Comment by williballenthin** [comment]
```
resolve DNS
  FAIL: doesn't match on referenced example: Fix the rule logic or provide a different example

allocate user process RWX memory
  FAIL: doesn't match on referenced example: Fix the rule logic or provide a different example

delete registry key
  FAIL: doesn't match on referenced example: Fix the rule logic or provide a different example

    (nursery) references DNS over HTTPS endpoints
      WARN: filename doesn't match the rule name: Rename rule file to match the rule name, expected: "references-dns-over-https-endpoints.yml", found: "reference-dns-over-https-endpoints.yml"

get session integrity level
  FAIL: doesn't match on referenced example: Fix the rule logic or provide a different example

simulate CTRL ALT DEL
  FAIL: doesn't match on referenced example: Fix the rule logic or provide a different example

reference anti-VM strings
  FAIL: doesn't match on referenced example: Fix the rule logic or provide a different example

check for unmoving mouse cursor
  FAIL: doesn't match on referenced example: Fix the rule logic or provide a different example

get Program Files directory
  FAIL: doesn't match on referenced example: Fix the rule logic or provide a different example
```

**Review by mr-tz — APPROVED** [review]
🚀

**Pull request merged**
